local db = require("dashboard")
db.preview_file_path = "./header.txt"
db.preview_file_height = 12
db.preview_file_width = 80
db.custom_center = {
	{
		icon = "  ",
		desc = "Recent Files",
		action = "Telescope oldfiles",
	},
	{
		icon = "  ",
		desc = "Find File  ",
		action = "Telescope find_files find_command=rg,--hidden,--files",
	},
	{
		icon = "  ",
		desc = "Find Word  ",
		action = "Telescope live_grep",
	},
	{
		icon = "  ",
		desc = "New file   ",
		action = "ene",
	},
	{
		icon = "  ",
		desc = "Quit Neovim",
		action = "qa",
	},
}

db.custom_header = {
	"XXXK0kkkkxxxxxk0XXXXNXNXXXXX0Okkkkkkkkkxxxdolc::;;;;;;;;;:::::::::::ccloddddxxxxxxxkkkkOKXNNNNNNNNNNXKOkkkkkkkkkOOOKXNNX",
	"XXXKOkxxxxxxxxO0XXNXNXXXXXXK0Okkkkkxxxdol:;,,'',,,;;,',,''..''',,;;,,,,;;:clooddxxxxkkkOKXNNNNNNNNNNXKOkkkkkkkkkOO0KXNNX",
	"XXX0OkxxxxxxxkO0XXNXXXXXXXXK0kkkkxxdoc:;,''''''',,,;;:clc;'......',,,,,,'''',;cldxxxkkkO0XXXXNXNNNNNXKOOkkkkkkkOOOOKXNXK",
	"XXKOkkkkkkkkkkO0XXXXXXXXXXXK0kxxxoc;,'''.....';:cloddxkkxdlc::;,'...'',,''''''',;ldxxxkO0XXXXXXXNNNXXKOOkkkkkkkOkOOKXNXK",
	"K0OkkkkkkkkkkkO0XXXXXXXXXXXKOkdl:,''''...';codxkkkOOOOOOOOOkxxxdol:;'''''''''''''';codxO0KXXXXXXNNNXX0OkkkkkkkkkkOOKXXK0",
	"OOkkkkkkkkkkkkO0XXXXXXXXXKK0ko:,'','.',:ldxkkkOOOOOOOOOOOOOOOOOOkkxdlc;,'''..''''''',:ok0KXXXXXXNXXXX0OkkkkkkkkkkOOKXXKO",
	"kkkkkkkkkxxxxkO0XXXXXXXKKK0xc,''','',:oxkkkOOOOOOOOOOOOOOOOOOOOOOkkkxxoc;''''..'.'''',;lkKXXXXXXXXXXX0OkkkkkkkkOkOO00K0O",
	"xkkkkkxxxxxxxkO0KXXXXXXK0kl,''''''':oxkkOOOOOOO000000000OOOOOOOOOOOOkkkxo:,,,'...''.'''':d0KKXXXXXXXK0OkkkkkkkkkOOOOOOOO",
	"kkkkkkkxxxxxxkO0KXXKKKK0d:,'''.'';oxxkOOOOOOO000000000000OO000OOOOOOOOOkxdc;,,''...'''''',lOKKXXXXXXK0OkkkkkkkkkkOOOOOOO",
	"kkkkkkkxxxxkkkO0KXXXXKOo;'''..',cdkkkOOOOOO0000000000000000000000OOOOOOOkkxo:,,''...''''''':xKXXXXXXX0OkkkkkkkkkkkOOOOOk",
	"kkxxxxkkkkkkkkO0KXXKKkl,''..',:oxkkkkOOOOO00000000000000000000000OOOOOOOOkkxo:,,''......'''';dKXXXXXK0Okkkkkkkkkkkkkkkkk",
	"0OkxxxkkkkkkkkO0KKK0kc'.''.';ldkkkkkOOOOOO0000KKKKKKKKK000000000OOOOOOOOOOkkko:,'''......'''',o0XXXXK0Okkkkkkkkkkkkkkkkk",
	"XK0OkxxxkkkkkkO0KKKkc'.''.':oxxkkkOOOOOOO00000KKKKKKKKK00KK0000OOOOOOOOOOOOkkxd:,'''.......''',o0XXXK0kkkkkkkkkkkkkkkkkk",
	"XXK0OkxxkkkkkkO0KKOl,.'''':dxxkkkkOOOOOOOO000000KKK000000000000OOOOOOOOOOOkkkkxo:,'''.......''',o0XXK0OkkkkOOkkkkOkkkkOO",
	"XXXX0OkxkkkkkkO0K0o,.'''';oxxkkkkkOOOOOO000000000000000K000000000OOOOOOOOOOkkkkxo:,''..........',dKKK0OkkkkOOOkOOOkkkOOO",
	"XXXXK0OkkkkkkkO00x:..''''cdxxkkkkkOOOOOO00000000000000K00000000000OOOOOOOOOOkkkxxo;,''..........';xKK0OkkkOOOkkkkkkkkkOO",
	"XXXXXKOkkkkkkkOOkl,..''.,lxxxkxkkkOOOOOOO00000000KKK000000000000OOkxxxdddoddxkkxxdc,,'...........';xK0OkkkkkkkkkkkkkkkkO",
	"XXXXXKOkxkxkkkkOx:'..'..;ldxxxxkkxxxxxxxxxxk00000KKKKKKK0000OOkxdlcc:::::::ccloxxxo:,'............':k0OkkkkkkkkkkkkkkOOO",
	"XXXXXKOkxkxkkkkko,......;oxxxxkxdlccc::::ccodxxkO000000000Okxddoollccc::::cccccloxdc;'............''ckOkkkkkkkkkkkOOOOOO",
	"XXXXK0kxxkkkkkkx:'..'...:dddxxoc:::::;:cclooddxxkOO000000Okxxxxxxxxxxxxxxxddddoooddo:'.............',okkkkkkkkOOOOOOOOOO",
	"XXXXKOkkkkkkkkko,''''...cdxxdl:;::clddddxxxxxxxxkkO00000OkxxxkkkOOOOOOOkkkkxxxddodddc,'.......'....'';dkkkkkkOOOOOOOOOOO",
	"XXXK0Okkkkkxkkx:'''''...cdxxdolooodxkkOOOOOOOOkkkkO00000OkxkkkOOOOOkkkkkxkkkxxddddddl:'......''''...''cxkkkkkOOOOOOOOOOO",
	"XXK0Okkkkkkkkko,'''''...cdxxdooddxxkkkkxxxkkOO0OOkOO0000OxxkOOOkdddl::;;:lllodxxxxddoc,......''''...'';dkkkkOOOOOOOOOOOO",
	"KKOOkkkkkkkkkkl'''''''..cdxdddxxddollc;;;;:oddxOOkkO0000OkxkOOxoldko:;;:loc::lodxxxxdl;'.'...'',''..'''ckkkkOOOOOOOOOOOO",
	"0Okkkkkkkkkkkx:'',,''...cdxxxxxdoc::oo:;;;cdddxkOkkO0000OkkkOOkkkxxxxxxxxxxdddxxkkkkxl;'.''..'',,'....';dOkkkkkOOOOOOOOO",
	"kkkkOOO0OO000d,',''''..'ldxkkkxdoodxxxxxxxxxkkOOkkkO0000OOkkkOOO0OOOOkkkkkkkOOOOOkkkxo:''''...''''.....'o0000000OOOOOkkk",
	"kkkk00KKKKKK0o'','',...'cdxkkkkkkkkkkkkkkkOO00OOkkkO000OOkkkOOOO0K000000OOO000OOOkkkko:,'''...''''......:kKKXXKK0Okkkkkk",
	"kxxkO00000OOkc''''''...'ldxkkkkkOOOOOOOOOO0000OOkkkO0000kkkkkkkO00KKK000000000OOOOkkkdc,''''..''''......,okOOOOOOkkkkkkk",
	"kxxxkkkkkkxko;.''',,'..'ldxkkkkOOOOOO00000000OOOkkkO0K00OkkkkkkOO00KKKKKK00000OOOkkkkxl,'''''..'''......'lxkkkkkkkkkkkkk",
	"kkkkkkkxxxxxl'.'''','..'cdxkkkkOOO00000000000OOOkkkO00K00OkxxxkkO000KKKKKK0000OOkkkkkxl,'''''..'''.......:xkkkkkkkkkkkkk",
	"kkkkkkkkkkxxc'.''''''...cddxkkkkO000000000000OOkkkkO00000OkxxxkkkkO00KK000000OOOkkkxxxl;'''.'...''.......;dxkkkkkkkkkkkk",
	"OOOOkkkkkkkd:..'''''....;odxxkkkO00000000000OOkkOkkkO0K00OkkkkOkxxxkkO00KK000OOkkxxxxdl;''......''.......;oxkkkkOOOOOOOO",
	"KKKKKKK000Ox:''''..'....,ldxxkkkO000000000OkkkkkOkkkO000OkxdddxxxdxkkkO00000OOOkxxxxxoc,''...............;dO000KKKKKKKKK",
	"KXXXXXXK0OOd,..'''''....':odxxkkOOO00000OOkkkkxxdoodxkxxdocccllodxkOOOkOOOOOOOkkxxxxdoc;'''..'..........':x0KKXXXXK00O00",
	"KKXXXXXK0kxl'..'''''.....:oodxxkkOOOOOOOOkkOOkkdoooooolcccllccclodxkOOOOOOOOOkkkxxxxdoc;''...''.........':x00KKXXK0kkxxk",
	"0KXXXXXK0kd:'..'''''.....;odddxxkkOOOOOkkOOOkxdlccccccclc:;;,,',;::ldkkOOOOOkkkkxxxxdlc;'...............':x00KKXXKOkxxxx",
	"O0KXXXXK0Od;...'''''.....;loddxxxkkkkkkOOkxol:;,,,,,,',:;''''..'''',;codkOOOkkkkkkxdol:;'...............':x00KKXXKOkkxkk",
	"O0KXXXXX0Oo;..''''''.....,coddxxkkkkkkOOxl:;;,',,;;::;colc;,,,,;;,;,,,;cdkOOOkkkxxxdol:,'...............':xO0KKXXKOkkkkk",
	"0KKXXXXK0Oo,..''','''....':lodxxkkkOOOkdc;,;;;;;;;:::cllllc:;;;;;;:::,,:lxkOOkkkxddol:;,'...............,cxO00KXXK0Okkkk",
	"0K00KXKKKkl,...'''','.....,clloxxkkOOOxl;,,;:c::cclloodddxdddddoooooo:,;cdkOOkxxdooc:;,'...............',cxO00KKKK0Okkkk",
	"00O0KKKK0xc'..''''','.....';cloodxkkkkxl;,;coddxxxkkkkkkOOOkkkkkkkkkd:,;lxkkkxddool:;,'..........'.....';cxkO00KKKOOkkkk",
	"0Okk0KKKOd:...''''','......';cllodddxxdc;;cxkkxxxdddoodddooddddxxkkxlcccldxdddooooc:;,'..........'....'',lxO00KKK0Okkkkk",
	"0OkkO0KOxl;'..'''''''.......';:cloooool:,;oxkOOkxdoc::;;:::cllodxxkxxdollloolllllc:;,'...........'......';loxOKKK0Okkkkk",
	"OkxkkOOkoc;'..'''''''........',:ccclllc,';ldxOOOkxdll:,',:cooodxkkkOOkxoolllllllc;,'.............''.....',;:cldk00Okkkkk",
	"Okxxxkkdl:,...'''''''.........',;:::c::,,:cldkkOOkxolc;,,:ldxdxkkOOkOkdoolccllc:;,...............''......',::ccloxkkkOOO",
	"kkxxxkxoc;,...''''''''..........'',,;;;,;;clodkOkxxddoc;;:ldxxdxkkkkkkxol:;:::;,'..............'.........',;::ccccldkkkk",
	"kkxxxkxdc;,...'''''''...... ........'',,,,:cllddolodddlccclddddxxdoooool:;;;;''................'..........'';:ccclllldkO",
	"kxxxkkxdl;'..'''','''..................'',,;:cllc:cloolcloooooooolcc:::;,,,'......''...........'............';ccllllccox",
	"kkkxxkxdl;'....''''''....................''',::c:;;:ccccoolllolllc:;,,,'''.....',;;,......'.................';cclllccccc",
	"kkkxxxxdl;'.'...'''''.......................'',;,,,,;;;:c:cc:::::;;''''.......,:cc;'.....'''................';cclllccccc",
	"kkkxxxxdc,.....'''''''...............','........',,',,',,,;;,,','''.........,:cllc;....'''''................';:clllcccc:",
	"kkxxxxxo:,.....'''''''.'.............,;;,'.......''.''''''''''............';cloolc,.....''''................';:clllllccc",
}
